fichas = [
[2758190,' DER SST CUL FIS INV ETI ','INV','DER','ETI','CUL','SST','FIS','','',0,'TIC MAT COM EMP DER SST CUL FIS INV ETI ',],
[2758230,' CIE SST INV CUL DER ETI ','ETI','INV','CIE','CUL','SST','DER','','',0,'TIC COM MAT EMP CIE SST INV CUL DER ETI ',],
[2758333,' FIS INV SST ETI CUL DER','INV','FIS','ETI','CUL','SST','DER','','',0,'MAT TIC COM EMP FIS INV SST ETI CUL DER',],
[2834649,' MAT CIE SST INV CUL DER ETI EMP ','INV','MAT','CIE','EMP','SST','ETI','CUL','DER',1,'TIC COM MAT CIE SST INV CUL DER ETI EMP ',],
[2834650,' MAT CIE SST INV CUL DER ETI EMP ','INV','MAT','CIE','CUL','SST','ETI','DER','EMP',1,'TIC COM MAT CIE SST INV CUL DER ETI EMP ',],
[2834651,' MAT CIE SST INV CUL DER ETI EMP ','EMP','MAT','CIE','CUL','SST','ETI','INV','DER',1,'TIC COM MAT CIE SST INV CUL DER ETI EMP ',],
[2834838,' MAT FIS INV SST ETI CUL EMP DER','INV','SST','MAT','CUL','ETI','FIS','EMP','DER',1,'TIC COM MAT FIS INV SST ETI CUL EMP DER',],
[2834839,' MAT TIC FIS SST ETI CUL EMP DER','TIC','ETI','MAT','CUL','FIS','SST','EMP','DER',1,'COM INV MAT TIC FIS SST ETI CUL EMP DER',],
[2834840,' MAT TIC FIS SST ETI CUL EMP DER','TIC','ETI','MAT','EMP','CUL','FIS','SST','DER',1,'COM INV MAT TIC FIS SST ETI CUL EMP DER',],
[2834841,' MAT TIC FIS SST ETI CUL EMP DER','TIC','CUL','MAT','ETI','FIS','SST','EMP','DER',1,'COM INV MAT TIC FIS SST ETI CUL EMP DER',],
[2834842,' MAT TIC FIS SST ETI CUL EMP DER','TIC','SST','MAT','CUL','ETI','FIS','DER','EMP',1,'COM INV MAT TIC FIS SST ETI CUL EMP DER',],
[2834843,' MAT TIC FIS SST ETI CUL EMP DER','CUL','TIC','MAT','EMP','ETI','DER','FIS','SST',1,'COM INV MAT TIC FIS SST ETI CUL EMP DER',],
[2834844,' MAT TIC FIS SST ETI CUL EMP DER','CUL','TIC','MAT','ETI','FIS','SST','EMP','DER',1,'COM INV MAT TIC FIS SST ETI CUL EMP DER',],
[2834845,' MAT TIC FIS SST ETI CUL EMP DER','CUL','TIC','MAT','DER','ETI','SST','FIS','EMP',1,'COM INV MAT TIC FIS SST ETI CUL EMP DER',],
[2834846,' MAT TIC FIS INV SST ETI CUL EMP DER','EMP','INV','TIC','ETI','MAT','DER','FIS','SST CUL',2,'COM MAT TIC FIS INV SST ETI CUL EMP DER',],
[2834847,' MAT TIC FIS INV COM SST CUL EMP DER','EMP','INV','COM','MAT','TIC','SST','FIS','CUL DER',2,'ETI MAT TIC FIS INV COM SST CUL EMP DER',],
[2834848,' MAT TIC FIS INV COM SST CUL EMP DER','EMP','INV','COM','MAT','TIC','SST','CUL','FIS DER',2,'ETI MAT TIC FIS INV COM SST CUL EMP DER',],
[2834849,' MAT TIC FIS INV COM SST CUL EMP DER','DER','INV','TIC','COM','EMP','SST','MAT','FIS CUL',2,'ETI MAT TIC FIS INV COM SST CUL EMP DER',],
[2834850,' MAT TIC FIS INV COM SST CUL EMP DER','DER','INV','COM','EMP','MAT','TIC','CUL','FIS SST',2,'ETI MAT TIC FIS INV COM SST CUL EMP DER',],
[2834851,' MAT TIC FIS INV COM SST CUL EMP DER','DER','INV','TIC','COM','EMP','SST','MAT','FIS CUL',2,'ETI MAT TIC FIS INV COM SST CUL EMP DER',],
[2834852,' MAT TIC FIS INV COM SST CUL EMP DER','DER','INV','TIC','COM','FIS','MAT','CUL','SST EMP',2,'ETI MAT TIC FIS INV COM SST CUL EMP DER',],
[2834853,' MAT TIC FIS INV COM SST CUL EMP DER','INV','COM','TIC','MAT','CUL','FIS','SST','EMP DER',2,'ETI MAT TIC FIS INV COM SST CUL EMP DER',],
[2834854,' MAT TIC FIS INV COM SST CUL EMP DER','INV','COM','TIC','EMP','MAT','SST','CUL','FIS DER',2,'ETI MAT TIC FIS INV COM SST CUL EMP DER',],
[2834855,' MAT TIC FIS INV COM SST CUL EMP DER','INV','COM','TIC','EMP','MAT','CUL','DER','FIS SST',2,'ETI MAT TIC FIS INV COM SST CUL EMP DER',],
[2834856,' MAT TIC FIS INV COM SST CUL EMP DER','INV','COM','TIC','MAT','CUL','EMP','SST','FIS DER',2,'ETI MAT TIC FIS INV COM SST CUL EMP DER',],
]

for ficha in fichas:
    if ficha[0] in [2758230, 2834649, 2834650, 2834651]:
        competencias = 'MAT COM TIC INV CIE CUL ETI SST EMP DER'.split()
    else:
        competencias = 'MAT COM TIC INV FIS CUL ETI SST EMP DER'.split()
    todas = ficha[11].split()
    for com in competencias:
        try:
            todas.remove(com)
        except:
            print(ficha[0], com)
    programadas = ficha[1].split()
    for n in [2,3,4,5,6,7,8,]:
        if ficha[n] != '':
            try:
                programadas.remove(ficha[n])
            except:
                print(ficha[0], ficha[n])
    print(ficha[0], programadas, ficha[9])
    
